### ISSUE TITLE
Platform error media_player.rn301 - Integration 'rn301' not found

### ISSUE THREAD

**Issue by gaborpetras** [arcao/homeassistant-rn301#1]
Hi!
When I try to setup the component I have an issue.
When I try to restart HA I get an error message : Platform error media_player.rn301 - Integration 'rn301' not found.

rn301 folder is copied to ha custom  components folder
my ha version is 2022.9.7
my config file looks like this:
media_player:
  - platform: rn301
    name: "Yamaha R-N301"
    host: 192.168.0.101

Can you please help me out?

**Comment by Neubda** [comment]
Hi!
After placing the files under /config/custom_components/rn301/ I had to restart the HA before I was able to configure the R-N301

**Comment by gaborpetras** [comment]
This solved the issue, thank you!
